"""``govops init`` — scaffold a new jurisdiction from canonical shape templates.

Phase H of v3 (per PLAN-v3 §Phase H): the adoption substrate. A non-engineer
program leader runs::

    govops init pl --shapes oas,ei

and gets a complete ``lawcode/pl/`` skeleton with TODO markers at every place
that needs jurisdiction-specific work. The skeleton is schema-valid the
moment it lands — every file passes the Phase 5 validator — so the
contributor's first ``pytest`` confirms the structure before they touch a
single statutory citation.

Refusal posture: the command never overwrites existing files. If any target
already exists, the entire scaffold is aborted with an error listing the
collisions, so accidentally re-running ``init`` over real work cannot
silently destroy it.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Iterable

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_LAWCODE_DIR = REPO_ROOT / "lawcode"


SUPPORTED_SHAPES = ("oas", "ei")


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class InitError(RuntimeError):
    """Scaffold cannot be generated as requested."""


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------


def _normalize_country_code(raw: str) -> str:
    code = raw.strip().lower()
    if not code:
        raise InitError("Country code must not be empty.")
    if not code.isalpha() or len(code) > 6:
        raise InitError(
            f"Country code {raw!r} must be 1–6 ASCII letters (ISO-style)."
        )
    return code


def _check_no_collisions(targets: list[Path]) -> None:
    existing = [t for t in targets if t.exists()]
    if existing:
        rels = "\n  ".join(str(p) for p in existing)
        raise InitError(
            "Refusing to overwrite existing files. Remove them or pick a "
            f"different country code:\n  {rels}"
        )


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------


def _jurisdiction_yaml(code: str) -> str:
    """Per-jurisdiction metadata file. Mirrors the shape used by v2 callers."""
    return f"""# yaml-language-server: $schema=../../schema/lawcode-v1.0.json
# Jurisdiction metadata for {code.upper()} — generated by `govops init`.
#
# TODO: replace placeholder values with the actual jurisdiction's data.
#       Every TODO line below is a hand-fill point.

defaults:
  domain: ui
  jurisdiction_id: {code}-TODO_PROGRAM
  effective_from: '1900-01-01'
values:
  - key: jurisdiction.{code}.label.en
    value: TODO Jurisdiction Name (English)
    value_type: string
  - key: jurisdiction.{code}.howto_url
    value: https://TODO-link-to-official-program-page
    value_type: string
"""


def _oas_program_yaml(code: str) -> str:
    """Old Age Pension manifest skeleton."""
    upper = code.upper()
    return f"""# yaml-language-server: $schema=../../../schema/program-manifest-v1.0.json
#
# {upper} — Old-Age Pension program manifest (generated by `govops init`).
#
# TODO: replace every TODO marker with jurisdiction-specific content.
# Per ADR-014, structure lives here; parameter values live in
# lawcode/{code}/config/oas-rules.yaml. Per ADR-015, `shape` references
# the canonical published shape catalog at schema/shapes/.

schema_version: "1.0"
program_id: oas
jurisdiction_id: jur-{code}-national
shape: old_age_pension
status: active

name:
  en: TODO Program Name (English)

description:
  en: TODO one-paragraph description of the program in English.

authority_chain:
  - id: auth-{code}-oas-constitution
    layer: constitution
    title: TODO Constitution title
    citation: TODO Constitutional citation
    effective_date: 1900-01-01
    url: https://TODO-link-to-constitution
  - id: auth-{code}-oas-act
    layer: act
    title: TODO Pension Act title
    citation: TODO Act citation
    effective_date: 1900-01-01
    url: https://TODO-link-to-act
    parent: auth-{code}-oas-constitution
  - id: auth-{code}-oas-program
    layer: program
    title: TODO Program-administering authority
    citation: TODO statute or regulation conferring authority
    parent: auth-{code}-oas-act
  - id: auth-{code}-oas-determination
    layer: service
    title: TODO Initial-eligibility determination service name
    citation: TODO procedural citation
    parent: auth-{code}-oas-program

legal_documents:
  - id: doc-{code}-oas-act
    type: statute
    title: TODO Act title
    citation: TODO Act citation
    effective_date: 1900-01-01
    sections:
      - id: sec-{code}-oas-1
        ref: TODO § number
        heading: TODO section heading
        text: >-
          TODO verbatim or near-verbatim section text in the source language.

rules:
  - id: rule-oas-age
    rule_type: age_threshold
    description: TODO Minimum age threshold (e.g. "Age 65 or older")
    formal_expression: applicant.age >= min_age
    citation: TODO § number
    source_document_id: doc-{code}-oas-act
    source_section_ref: TODO § number
    param_key_prefix: {code}-oas.rule.age
    parameters:
      min_age: {{ ref: {code}-oas.rule.age.min_age }}

  - id: rule-oas-residency
    rule_type: residency_minimum
    description: TODO Minimum years of residency / contributions after 18
    formal_expression: years_in_country_after_18 >= min_years
    citation: TODO § number
    source_document_id: doc-{code}-oas-act
    source_section_ref: TODO § number
    param_key_prefix: {code}-oas.rule.residency
    parameters:
      min_years: {{ ref: {code}-oas.rule.residency.min_years }}
      home_countries: {{ ref: {code}-oas.rule.residency.home_countries }}

  - id: rule-oas-legal-status
    rule_type: legal_status
    description: TODO Citizenship / permanent-residence requirement
    formal_expression: "applicant.legal_status in accepted_statuses"
    citation: TODO § number
    source_document_id: doc-{code}-oas-act
    source_section_ref: TODO § number
    param_key_prefix: {code}-oas.rule.legal-status
    parameters:
      accepted_statuses: {{ ref: {code}-oas.rule.legal-status.accepted_statuses }}

  - id: rule-oas-evidence
    rule_type: evidence_required
    description: TODO Required evidence documents (e.g. birth certificate)
    formal_expression: has_evidence(required_types)
    citation: TODO § number
    source_document_id: doc-{code}-oas-act
    source_section_ref: TODO § number
    param_key_prefix: {code}-oas.rule.evidence
    parameters:
      required_types: {{ ref: {code}-oas.rule.evidence.required_types }}

demo_cases:
  # TODO: 4 demo cases per the contribution guide:
  #   1. Eligible (full benefit)
  #   2. Ineligible (e.g. under age threshold)
  #   3. Eligible (partial benefit, if program has partial-pension shape)
  #   4. Insufficient evidence
  - id: demo-{code}-oas-001
    applicant:
      id: app-{code}-oas-001
      date_of_birth: 1955-01-01  # TODO realistic DOB for the eligible case
      legal_name: TODO Applicant Name
      legal_status: citizen
      country_of_birth: {upper}
    residency_periods:
      - country: TODO Country name
        start_date: 1955-01-01
        verified: true
    evidence_items:
      - id: ev-{code}-oas-001-bc
        type: birth_certificate
        description: TODO description in source language
        provided: true
        verified: true
"""


def _oas_config_yaml(code: str) -> str:
    upper = code.upper()
    return f"""# yaml-language-server: $schema=../../../schema/lawcode-v1.0.json
# {code}/config/oas-rules.yaml — substrate values for {upper} OAS.
#
# TODO: replace every TODO with jurisdiction-specific values + citations.

defaults:
  domain: rule
  jurisdiction_id: {code}-oas
  effective_from: '1900-01-01'
values:
  - key: {code}-oas.rule.age.min_age
    value: 65   # TODO actual minimum age
    value_type: number
    citation: TODO § number

  - key: {code}-oas.rule.residency.min_years
    value: 10   # TODO actual minimum years
    value_type: number
    citation: TODO § number
  - key: {code}-oas.rule.residency.home_countries
    value: [{upper}]   # TODO ISO codes counted as "home"
    value_type: list

  - key: {code}-oas.rule.legal-status.accepted_statuses
    value: [citizen, permanent_resident]
    value_type: list

  - key: {code}-oas.rule.evidence.required_types
    value: [birth_certificate]   # TODO required evidence types
    value_type: list
"""


def _ei_program_yaml(code: str) -> str:
    upper = code.upper()
    return f"""# yaml-language-server: $schema=../../../schema/program-manifest-v1.0.json
#
# {upper} — Employment Insurance program manifest (generated by `govops init`).
#
# TODO: replace every TODO marker with jurisdiction-specific content.

schema_version: "1.0"
program_id: ei
jurisdiction_id: jur-{code}-national
shape: unemployment_insurance
status: active

name:
  en: TODO Employment Insurance program name (English)

description:
  en: TODO one-paragraph description in English.

authority_chain:
  - id: auth-{code}-ei-constitution
    layer: constitution
    title: TODO Constitution title
    citation: TODO Constitutional citation
    effective_date: 1900-01-01
    url: https://TODO-link
  - id: auth-{code}-ei-act
    layer: act
    title: TODO Employment Insurance Act title
    citation: TODO Act citation
    effective_date: 1900-01-01
    url: https://TODO-link
    parent: auth-{code}-ei-constitution
  - id: auth-{code}-ei-program
    layer: program
    title: TODO program-administering authority
    citation: TODO conferring statute
    parent: auth-{code}-ei-act
  - id: auth-{code}-ei-determination
    layer: service
    title: TODO EI Initial Eligibility Determination
    citation: TODO procedural citation
    parent: auth-{code}-ei-program

legal_documents:
  - id: doc-{code}-ei-act
    type: statute
    title: TODO Act title
    citation: TODO Act citation
    effective_date: 1900-01-01
    sections:
      - id: sec-{code}-ei-1
        ref: TODO § number
        heading: TODO section heading
        text: >-
          TODO verbatim section text in the source language.

rules:
  - id: rule-ei-contribution
    rule_type: residency_minimum
    description: TODO Minimum contribution period (e.g. "12 months in last 30")
    formal_expression: insured_months >= min_months
    citation: TODO § number
    source_document_id: doc-{code}-ei-act
    source_section_ref: TODO § number
    param_key_prefix: {code}-ei.rule.contribution
    parameters:
      min_years: {{ ref: {code}-ei.rule.contribution.min_years }}
      home_countries: {{ ref: {code}-ei.rule.contribution.home_countries }}

  - id: rule-ei-legal-status
    rule_type: legal_status
    description: TODO Right-to-work requirement
    formal_expression: "applicant.legal_status in accepted_statuses"
    citation: TODO § number
    source_document_id: doc-{code}-ei-act
    source_section_ref: TODO § number
    param_key_prefix: {code}-ei.rule.legal-status
    parameters:
      accepted_statuses: {{ ref: {code}-ei.rule.legal-status.accepted_statuses }}

  - id: rule-ei-evidence
    rule_type: evidence_required
    description: TODO Required dismissal evidence (in the source language)
    formal_expression: has_evidence(required_types)
    citation: TODO § number
    source_document_id: doc-{code}-ei-act
    source_section_ref: TODO § number
    param_key_prefix: {code}-ei.rule.evidence
    parameters:
      required_types: {{ ref: {code}-ei.rule.evidence.required_types }}

  - id: rule-ei-duration
    rule_type: benefit_duration_bounded
    description: TODO Maximum benefit duration in weeks
    formal_expression: weeks_total <= max_weeks
    citation: TODO § number
    source_document_id: doc-{code}-ei-act
    source_section_ref: TODO § number
    param_key_prefix: {code}-ei.rule.duration
    parameters:
      weeks_total: {{ ref: {code}-ei.rule.duration.weeks_total }}
      start_offset_days: {{ ref: {code}-ei.rule.duration.start_offset_days }}

  - id: rule-ei-job-search
    rule_type: active_obligation
    description: TODO Active job-search / availability obligation
    formal_expression: available_for_placement AND active_cooperation
    citation: TODO § number
    source_document_id: doc-{code}-ei-act
    source_section_ref: TODO § number
    param_key_prefix: {code}-ei.rule.job-search
    parameters:
      obligation_id: {{ ref: {code}-ei.rule.job-search.obligation_id }}
      cadence: {{ ref: {code}-ei.rule.job-search.cadence }}

demo_cases:
  - id: demo-{code}-ei-001
    applicant:
      id: app-{code}-ei-001
      date_of_birth: 1990-01-01  # TODO realistic DOB
      legal_name: TODO Applicant Name
      legal_status: citizen
      country_of_birth: {upper}
    residency_periods:
      - country: TODO Country name
        start_date: 1990-01-01
        verified: true
    evidence_items:
      - id: ev-{code}-ei-001-bc
        type: birth_certificate
        description: TODO
        provided: true
        verified: true
      - id: ev-{code}-ei-001-tax
        type: tax_record
        description: TODO contribution record
        provided: true
        verified: true
      - id: ev-{code}-ei-001-roe
        # TODO replace `dismissal_certificate` with the local term
        # (record_of_employment / arbeitsbescheinigung / certificado_empresa / …)
        type: dismissal_certificate
        description: TODO dismissal evidence in source language
        provided: true
        verified: true
"""


def _ei_config_yaml(code: str) -> str:
    upper = code.upper()
    return f"""# yaml-language-server: $schema=../../../schema/lawcode-v1.0.json
# {code}/config/ei-rules.yaml — substrate values for {upper} EI.
#
# TODO: replace every TODO with jurisdiction-specific values + citations.

defaults:
  domain: rule
  jurisdiction_id: {code}-ei
  effective_from: '1900-01-01'
values:
  - key: {code}-ei.rule.contribution.min_years
    value: 1   # TODO years equivalent of the contribution requirement
    value_type: number
    citation: TODO § number
  - key: {code}-ei.rule.contribution.home_countries
    value: [{upper}]
    value_type: list

  - key: {code}-ei.rule.legal-status.accepted_statuses
    value: [citizen, permanent_resident]
    value_type: list

  - key: {code}-ei.rule.evidence.required_types
    # TODO replace with the local term (record_of_employment / arbeitsbescheinigung / …)
    value: [dismissal_certificate]
    value_type: list
    citation: TODO § number

  - key: {code}-ei.rule.duration.weeks_total
    value: 26   # TODO realistic illustrative weeks
    value_type: number
    citation: TODO § number
  - key: {code}-ei.rule.duration.start_offset_days
    value: 0
    value_type: number

  - key: {code}-ei.rule.job-search.obligation_id
    value: {code}-ei-active-cooperation
    value_type: string
  - key: {code}-ei.rule.job-search.cadence
    value: monthly
    value_type: string
    citation: TODO § number
"""


# ---------------------------------------------------------------------------
# Plain-language doc generator (Phase H §"each manifest has a sibling .md")
# ---------------------------------------------------------------------------


def render_plain_language_doc(manifest_path: Path) -> str:
    """Produce a plain-language Markdown rendering of a program manifest.

    The intent is to give a non-coder program leader a readable summary of
    what the YAML actually encodes — every rule, citation, and demo case
    in prose. Run on every program manifest in the repo to maintain the
    Phase H convention; also called from ``govops init`` to seed the
    sidecar alongside a fresh manifest.
    """
    with manifest_path.open("r", encoding="utf-8") as fh:
        raw = yaml.safe_load(fh)
    if not isinstance(raw, dict):
        raise InitError(f"{manifest_path}: top-level must be a mapping.")

    program_id = raw.get("program_id", "?")
    jurisdiction_id = raw.get("jurisdiction_id", "?")
    shape = raw.get("shape", "?")
    name = raw.get("name", {}) or {}
    description = raw.get("description", {}) or {}
    authority = raw.get("authority_chain", []) or []
    rules = raw.get("rules", []) or []
    demos = raw.get("demo_cases", []) or []

    en_name = name.get("en") or next(iter(name.values()), program_id)
    en_desc = description.get("en") or next(iter(description.values()), "")

    lines: list[str] = []
    lines.append(f"# {en_name}")
    lines.append("")
    lines.append(
        "_This document is a plain-language rendering of the program manifest "
        f"(`{manifest_path.name}`) for non-coder review. The YAML next to it is "
        "the authoritative source the engine reads; this Markdown is generated "
        "from the same content and may be regenerated whenever the YAML "
        "changes._"
    )
    lines.append("")

    lines.append("## At a glance")
    lines.append("")
    lines.append(f"- **Program id**: `{program_id}`")
    lines.append(f"- **Jurisdiction**: `{jurisdiction_id}`")
    lines.append(f"- **Shape**: `{shape}`")
    if name:
        for lang, label in name.items():
            lines.append(f"- **Name ({lang})**: {label}")
    if en_desc:
        lines.append("")
        lines.append(en_desc)
    lines.append("")

    if authority:
        lines.append("## Authority chain")
        lines.append("")
        lines.append(
            "Where this program's authority comes from, top to bottom — "
            "constitution at the top, the specific service at the bottom."
        )
        lines.append("")
        for ref in authority:
            layer = ref.get("layer", "")
            title = ref.get("title", "")
            citation = ref.get("citation", "")
            lines.append(f"- **{layer}** — {title}  ")
            lines.append(f"  Citation: `{citation}`")
            url = ref.get("url")
            if url:
                lines.append(f"  Link: <{url}>")
        lines.append("")

    if rules:
        lines.append("## Rules the engine evaluates")
        lines.append("")
        lines.append(
            "Each rule is a condition the engine checks against a case. "
            "Parameter values come from the substrate "
            f"(`lawcode/.../config/{program_id}-rules.yaml`) and can be "
            "amended through the dual-approval workflow without touching "
            "this manifest."
        )
        lines.append("")
        for rule in rules:
            rule_id = rule.get("id", "?")
            rule_type = rule.get("rule_type", "?")
            desc = rule.get("description", "")
            citation = rule.get("citation", "")
            lines.append(f"### `{rule_id}` ({rule_type})")
            lines.append("")
            if desc:
                lines.append(f"> {desc}")
                lines.append("")
            if citation:
                lines.append(f"Citation: `{citation}`")
                lines.append("")
            params = rule.get("parameters") or {}
            if params:
                lines.append("Parameters (read from substrate at evaluation time):")
                lines.append("")
                for pname, pspec in params.items():
                    if isinstance(pspec, dict) and "ref" in pspec:
                        lines.append(f"- `{pname}` ← substrate key `{pspec['ref']}`")
                    elif isinstance(pspec, dict) and "include" in pspec:
                        lines.append(f"- `{pname}` ← include `{pspec['include']}`")
                    else:
                        lines.append(f"- `{pname}` = {pspec}")
                lines.append("")

    if demos:
        lines.append("## Demo cases")
        lines.append("")
        lines.append(
            "Synthetic applicants used by the test suite and the demo UI — "
            "no real personal data."
        )
        lines.append("")
        for case in demos:
            cid = case.get("id", "?")
            applicant = case.get("applicant") or {}
            label = applicant.get("legal_name") or "(unnamed)"
            status = applicant.get("legal_status", "?")
            lines.append(f"- **`{cid}`** — {label} ({status})")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Regenerate this file with `govops docs <manifest-path>` whenever the "
        "manifest changes."
    )
    lines.append("")
    return "\n".join(lines)


def write_plain_language_doc(manifest_path: Path) -> Path:
    """Write the sibling ``<id>.md`` for a manifest. Returns the doc path."""
    out = manifest_path.with_suffix(".md")
    text = render_plain_language_doc(manifest_path)
    out.write_text(text, encoding="utf-8")
    return out


# ---------------------------------------------------------------------------
# Scaffolder
# ---------------------------------------------------------------------------


def _select_shapes(raw_shapes: Iterable[str] | None) -> list[str]:
    if raw_shapes is None:
        return list(SUPPORTED_SHAPES)
    selected = [s.strip().lower() for s in raw_shapes if s.strip()]
    unknown = [s for s in selected if s not in SUPPORTED_SHAPES]
    if unknown:
        raise InitError(
            f"Unknown shape(s): {unknown}. "
            f"Supported: {list(SUPPORTED_SHAPES)}"
        )
    return selected or list(SUPPORTED_SHAPES)


def init_jurisdiction(
    code: str,
    *,
    shapes: Iterable[str] | None = None,
    lawcode_dir: Path | None = None,
) -> list[Path]:
    """Generate a complete ``lawcode/<code>/`` skeleton.

    Returns the list of files written, in creation order. Refuses if any
    target file already exists — partial scaffolds would leave the
    directory in an ambiguous state.
    """
    norm_code = _normalize_country_code(code)
    selected = _select_shapes(shapes)
    base = (lawcode_dir or DEFAULT_LAWCODE_DIR) / norm_code

    targets: dict[Path, str] = {}
    targets[base / "jurisdiction.yaml"] = _jurisdiction_yaml(norm_code)
    if "oas" in selected:
        targets[base / "programs" / "oas.yaml"] = _oas_program_yaml(norm_code)
        targets[base / "config" / "oas-rules.yaml"] = _oas_config_yaml(norm_code)
    if "ei" in selected:
        targets[base / "programs" / "ei.yaml"] = _ei_program_yaml(norm_code)
        targets[base / "config" / "ei-rules.yaml"] = _ei_config_yaml(norm_code)

    _check_no_collisions(list(targets.keys()))

    written: list[Path] = []
    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
        if path.suffix == ".yaml" and path.parent.name == "programs":
            doc = write_plain_language_doc(path)
            written.append(doc)
    return written


# ---------------------------------------------------------------------------
# CLI handlers
# ---------------------------------------------------------------------------


def _run_init(
    *,
    country_code: str,
    shapes: list[str] | None,
    lawcode_dir: str | None,
) -> int:
    try:
        targets = init_jurisdiction(
            country_code,
            shapes=shapes,
            lawcode_dir=Path(lawcode_dir) if lawcode_dir else None,
        )
    except InitError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print()
    print(f"  Scaffolded {len(targets)} file(s) for `{country_code.lower()}`:")
    for t in targets:
        print(f"    {t}")
    print()
    print(
        "  Next steps:\n"
        "    1. Replace every TODO marker with jurisdiction-specific content.\n"
        "    2. Run `pytest -q` — schema validation runs on every push.\n"
        "    3. Add the new code to `JURISDICTION_REGISTRY` if you need it\n"
        "       to appear in the demo UI's jurisdiction dropdown.\n"
    )
    return 0


def _run_docs(*, manifest_path: str) -> int:
    path = Path(manifest_path)
    if not path.exists():
        print(f"error: manifest not found: {path}", file=sys.stderr)
        return 2
    try:
        out = write_plain_language_doc(path)
    except InitError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(f"  Wrote {out}")
    return 0
